// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvb_lh9ntWyAv2105J-zToUa4MQVNznU8',
    appId: '1:187325753352:web:76d52a718514bf05b8c9bd',
    messagingSenderId: '187325753352',
    projectId: 'pharma-pos-ceb10',
    authDomain: 'pharma-pos-ceb10.firebaseapp.com',
    storageBucket: 'pharma-pos-ceb10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5JhBc7dnBetmkodd2Jbvo-M-dB-_FOdA',
    appId: '1:187325753352:android:bd2f4a35f217ecb2b8c9bd',
    messagingSenderId: '187325753352',
    projectId: 'pharma-pos-ceb10',
    storageBucket: 'pharma-pos-ceb10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfCgDn3OmyiWgCKioGl5k4MMJixWMG0c8',
    appId: '1:187325753352:ios:4b7cdab50eb23431b8c9bd',
    messagingSenderId: '187325753352',
    projectId: 'pharma-pos-ceb10',
    storageBucket: 'pharma-pos-ceb10.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfCgDn3OmyiWgCKioGl5k4MMJixWMG0c8',
    appId: '1:187325753352:ios:4b7cdab50eb23431b8c9bd',
    messagingSenderId: '187325753352',
    projectId: 'pharma-pos-ceb10',
    storageBucket: 'pharma-pos-ceb10.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvb_lh9ntWyAv2105J-zToUa4MQVNznU8',
    appId: '1:187325753352:web:802f24461bde7363b8c9bd',
    messagingSenderId: '187325753352',
    projectId: 'pharma-pos-ceb10',
    authDomain: 'pharma-pos-ceb10.firebaseapp.com',
    storageBucket: 'pharma-pos-ceb10.firebasestorage.app',
  );
}
